image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run example:build
  - yarn run example:publish

  artifacts:
    paths:
    - public
  
  only:
  - master